# for local development
version: '3.7'
services:
  dev:
    build:
      context: .
      target: 'develop-stage'
    ports:
    - '8889:80'
    volumes:
    - '.:/app'
    command: /bin/sh -c "yarn && quasar dev"
  prod:
    build:
      context: .
      target: 'production-stage'
    ports:
      - "80:80"
